imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    locales:
        - ru

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: ~
        #save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
            app_project_title:         "%project_title%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


# Third party bundles
assetic:
    bundles: [ AppBundle ]
    filters:
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

darvin_admin:
    locales: "%locales%"
    project:
        title: "%project_title%"
        url:   "%project_url%"

darvin_image:
    upload_path: "%image_upload_path%"

darvin_utils:
    mailer:
        from: "%mailer_from%"

darvin_order:
    order_types:
        -
            alias:  call
            entity: AppBundle\Entity\Order\Call
            form_type: AppBundle\Form\Type\Order\CallType
            template:
                form: :order/call:form.html.twig
                form_widget: :order/call/widget:form.html.twig
                submitted: :order/call/widget:submitted.html.twig
#        -
#            alias:  call_wide
#            entity: AppBundle\Entity\Order\Call
#            form_type: AppBundle\Form\Type\Order\CallType
#            template:
#                form_widget: :order/call_wide/widget:form.html.twig
#                submitted: :order/call_wide/widget:submitted.html.twig

vich_uploader:
    db_driver: orm
    mappings:
        darvin_image:
            uri_prefix:         "/%image_upload_path%"
            upload_destination: "%kernel.root_dir%/../web/%image_upload_path%"
            directory_namer:    darvin_image.namer.directory
            namer:              darvin_image.namer.file

darvin_menu:
    menus:
        -
            alias:       main
            breadcrumbs: true

knp_paginator:
    template:
        pagination: ::pagination.html.twig

