security:
    encoders:
        Darvin\UserBundle\Entity\BaseUser:
            algorithm:      pbkdf2
            hash_algorithm: sha512

    providers:
        user:
            entity:
                class:    Darvin\UserBundle\Entity\BaseUser
                property: email

    firewalls:
        admin_area:
            pattern:  ^/admin/
            provider: user
            form_login:
                check_path:           darvin_admin_security_login_check
                login_path:           darvin_admin_security_login
                default_target_path:  darvin_admin_homepage
                use_referer:          true
                csrf_token_id:        "%secret%"
                csrf_token_generator: security.csrf.token_manager
                remember_me:          true
            remember_me:
                name:     REMEMBERMEADMIN
                lifetime: 43200 # 12 hours
                secret:   "%secret%"
            logout:
                csrf_token_id: "%secret%"
                path:          darvin_admin_security_logout
                target:        darvin_admin_security_login
                handlers:
                   - darvin_ecommerce.cart_item.migrate_listener #(раскомментировать при использовании "darvinstudio/darvin-ecommerce-bundle")
            anonymous: ~
            oauth:
               resource_owners:
                    darvin_auth_admin: darvin_admin_security_darvin_auth_login_check
               login_path:   darvin_admin_security_login
               failure_path: darvin_admin_security_login
               oauth_user_provider:
                    service: darvin_admin.security.user_provider.oauth
               default_target_path: darvin_admin_homepage
               use_referer:         true
               check_path:          darvin_admin_security_darvin_auth_login_check
            switch_user: true

    role_hierarchy:
        ROLE_GUESTADMIN: [ ROLE_ADMIN ]
        ROLE_SUPERADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    access_control:
        - { path: "^/admin/login",  roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/admin/,         roles: [ ROLE_ADMIN ] }