# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    app.configuration:
        class: AppBundle\Configuration\AppConfiguration
        tags:
            - { name: darvin_config.configuration }

