extends: "@DarvinECommerceBundle/Resources/config/admin/product/property.yml"

children:
    - AppBundle\Entity\ECommerce\Product\AppPropertyValue

order_by:
    position: asc
sortable_fields:
    position: ~
    value:    ~

view:
    index:
        fields:
            before~title~position: ~
            appValues:
                condition: entity.isChoiceWithPrice()
                widget:
                    alias: child_links
                    options:
                        child_entity: AppBundle\Entity\ECommerce\Product\AppPropertyValue
            main:
                condition: entity.isChoiceWithPrice()
            brandDependent: ~
form:
    index:
        fields:
            position: ~
            main: ~
            brandDependent: ~
    edit:
        fields:
            type:
                type: choice
                options:
                    choices:           [ AppBundle\Entity\ECommerce\Product\AppProperty, getTypes ]
                    choices_as_values: true
                    attr:
                        class: type
